# Generated by Django 6.0 on 2025-12-18 01:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klub_user', '0003_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aladin_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klub_talk.author')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klub_talk.category')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='함께 책 읽고 소통해요', max_length=50)),
                ('description', models.TextField(blank=True, default='책을 읽고 함께 이야기를 나눌 분들을 찾습니다.')),
                ('members', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.book')),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.meeting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='절창의 남자 주인공 이름은?', max_length=50)),
                ('answer', models.CharField(default='오언', max_length=50)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.meeting')),
            ],
        ),
    ]
