# Generated by Django 4.1.12 on 2025-12-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='last_updated',
        ),
    ]
