# Generated by Django 4.2.27 on 2025-12-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='finished_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
