# Generated by Django 4.2.27 on 2025-12-22 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default='책을 읽고 함께 이야기를 나눌 분들을 찾습니다.', validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
