# Generated by Django 4.1.12 on 2025-12-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0002_remove_book_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='함께 책 읽고 소통해요', max_length=50),
        ),
    ]
