# Generated by Django 4.1.12 on 2025-12-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klub_user', '0002_user_email_alter_user_password'),
        ('klub_talk', '0003_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user'),
        ),
    ]
