# Generated by Django 6.0 on 2025-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0005_author_category_remove_book_author_book_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default='책을 읽고 함께 이야기를 나눌 분들을 찾습니다.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
