# Generated by Django 4.2.27 on 2025-12-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klub_user', '0003_user_status'),
        ('klub_talk', '0006_meeting_description_meeting_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.IntegerField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='절창의 남자 주인공 이름은?', max_length=50)),
                ('answer', models.CharField(default='오언', max_length=50)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.meeting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user')),
            ],
        ),
    ]
