# Generated by Django 4.1.12 on 2025-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
