# Generated by Django 4.2.27 on 2025-12-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='user', max_length=30),
        ),
    ]
