# Generated by Django 4.2.27 on 2025-12-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_user', '0004_rename_created_at_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
