# Generated by Django 4.2.27 on 2025-12-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klub_recommend', '0001_initial'),
        ('klub_talk', '0001_initial'),
        ('klub_user', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationresult',
            name='books',
            field=models.ManyToManyField(to='klub_talk.book'),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_recommend.readingpreference'),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user'),
        ),
        migrations.AddField(
            model_name='readingpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user'),
        ),
    ]
