# Generated by Django 4.2.27 on 2025-12-19 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klub_talk', '0007_meeting_members_quiz_participate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30)),
                ('new_vs_classic', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('mood', models.CharField(max_length=30)),
                ('reading_style', models.CharField(max_length=30)),
                ('length_pref', models.CharField(max_length=20)),
                ('difficulty_pref', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(to='klub_talk.book')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_recommend.readingpreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
