# Generated by Django 4.2.27 on 2025-12-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klub_user', '0003_user_status'),
        ('klub_recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user'),
        ),
        migrations.AlterField(
            model_name='recommendationresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_user.user'),
        ),
    ]
