# Generated by Django 4.2.27 on 2025-12-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klub_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
    ]
