# Generated by Django 4.2.27 on 2025-12-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klub_chat', '0001_initial'),
        ('klub_talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='klub_talk.meeting'),
        ),
    ]
