# Generated by Django 4.1.12 on 2025-12-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
