# Generated by Django 4.2.27 on 2025-12-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0003_alter_meeting_description_alter_quiz_answer_and_more'),
        ('klub_chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='klub_talk.meeting')),
            ],
            options={
                'unique_together': {('meeting',)},
            },
        ),
    ]
