# Generated by Django 4.2.27 on 2025-12-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0003_alter_meeting_description_alter_quiz_answer_and_more'),
        ('klub_chat', '0003_meetingalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingalert',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='meetingalert',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.meeting'),
        ),
    ]
