# Generated by Django 6.0 on 2025-12-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_chat', '0004_alter_chatmessage_id_alter_room_id'),
        ('klub_talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='klub_talk.meeting'),
        ),
    ]
