# Generated by Django 4.2.27 on 2025-12-23 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klub_talk', '0003_alter_meeting_description_alter_quiz_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klub_chat', '0004_rename_sent_at_meetingalert_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meetingalert',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingalert',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_talk.meeting'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'timestamp'], name='klub_chat_c_room_id_8b44fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingalert',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_user'),
        ),
    ]
